GestionFenetres:
    EcranPrincipal:
    EcranOption:

<EcranPrincipal>:
    name:"ecranprincipal"
    BoxLayout:
        
        Label:
            text:"Ecran principal"
        Button:
            text:"OPTIONS"
            on_release:
                app.root.current = "ecranoption"
                root.manager.transition.direction = "left"

<EcranOption>:
    name:"ecranoption"
    BoxLayout:
        Label:
            text:"Menu Option"
        Button:
            text:"Retour"
            on_release:
                app.root.current = "ecranprincipal"
                root.manager.transition.direction = "right"


